FROM python:3.11

RUN pip install --upgrade pip

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./speciesnet /app

WORKDIR /app

COPY ./entrypoint.test.sh /
RUN chmod +x /entrypoint.test.sh

ENTRYPOINT ["/entrypoint. test.sh"]
CMD ["python", "manage.py", "test", "species.tests", "-v", "2"]