services:

    db:
      container_name: ASN_DB 
      image: mariadb:latest
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: ${DATABASE_NAME-speciesnet}
        MYSQL_USER: ${DATABASE_USER-mysqluser}
        MYSQL_PASSWORD: ${DATABASE_PASSWORD-unsecure}
        MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD-unsecure}
      expose:
        - ${DATABASE_PORT-3306}
      volumes:
        - asn_data:/var/lib/mysql

    django_gunicorn:
      container_name: ASN_DJANGO
      restart: unless-stopped
      depends_on: 
        #- postgres_db
        - db
      volumes:
        - static:/static
        - media:/media
      env_file: 
        - ./.env
      build:
        context: .
      ports: 
        - 8000:8000

    nginx:
      container_name: NGINX_CBOT
      image: jonasal/nginx-certbot:5.2.1-nginx1.27.0
      build: ./nginx
      depends_on: 
        - django_gunicorn
      restart: unless-stopped
      env_file: 
        - ./.env
      ports:
        - ${HTTP_PORT-80}:80
        - ${HTTPS_PORT-443}:443
      volumes:
        - static:/static
        - media:/media
        - nginx_secrets:/etc/letsencrypt
        - ./user_conf.d:/etc/nginx/user_conf.d

volumes:
  static:
  media:
  nginx_secrets:
  asn_data:

