# Generated by Django 5.0.1 on 2024-01-26 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='lastUpdated',
        ),
        migrations.AddField(
            model_name='species',
            name='global_region',
            field=models.CharField(choices=[('SAM', 'South America'), ('CAM', 'Central America'), ('NAM', 'North America'), ('AFR', 'Africa'), ('SEA', 'Southeast Asia'), ('AUS', 'Australia'), ('OTH', 'Other Region')], default='AFR', max_length=3),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=240),
        ),
        migrations.CreateModel(
            name='SpeciesInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('unique_traits', models.CharField(max_length=200)),
                ('genetic_traits', models.CharField(choices=[('AS', 'Aquarium Strain'), ('WC', 'Wild Caught'), ('F1', 'F1'), ('F2', 'F2'), ('OT', 'Other')], default='AS', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='species.species')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
