# Generated by Django 5.0.6 on 2024-07-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
