# Generated by Django 5.0.6 on 2024-06-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_species_alt_name_species_common_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciesinstance',
            old_name='currently_keeping_species',
            new_name='currently_keep',
        ),
    ]
