# Generated by Django 5.0.6 on 2024-06-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0003_rename_currently_keeping_species_speciesinstance_currently_keep'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='photo_credit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
