# Generated by Django 5.1.6 on 2025-03-21 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0003_rename_is_private_user_is_private_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesinstance',
            name='enable_species_log',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='speciesinstance',
            name='year_acquired',
            field=models.IntegerField(blank=True, default=2025, null=True),
        ),
        migrations.CreateModel(
            name='SpeciesInstanceLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('log_entry_image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('log_entry_notes', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('speciesInstance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species_instance_log_entry', to='species.speciesinstance')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
