# Generated by Django 5.0.1 on 2024-02-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0003_alter_species_options_alter_speciesinstance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='species',
            name='local_distribution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speciesinstance',
            name='collection_point',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
