# Generated by Django 5.0.1 on 2024-02-19 11:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0004_species_collection_point_species_lastupdated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='species',
            name='species_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='speciesinstance',
            name='instance_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='speciesinstance',
            name='approx_date_acquired',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Acquired'),
        ),
        migrations.AlterField(
            model_name='speciesinstance',
            name='unique_traits',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='speciesinstance',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='species_instances', to=settings.AUTH_USER_MODEL),
        ),
    ]
