# Generated by Django 5.1.6 on 2025-05-07 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0004_speciesinstance_acquired_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SpeciesInstanceLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('text_line1', models.CharField(null=False, blank=True, max_length=100)),
                ('text_line2', models.CharField(null=False, blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('speciesInstance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species_instance_label', to='species.speciesinstance')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
