# Generated by Django 5.1.6 on 2025-07-10 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0005_user_is_admin_speciesinstancelabel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name'], 'verbose_name_plural': 'Species'},
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='bap_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='bap_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='species_instance_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speciesinstance',
            name='cares_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='cares_status',
            field=models.CharField(choices=[('NOTC', 'Undefined'), ('NEAR', 'Near Threatened'), ('VULN', 'Vulnerable'), ('ENDA', 'Endangered'), ('CEND', 'Critically Endangered'), ('EXCT', 'Extict in the Wild')], default='NOTC', max_length=4),
        ),
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.CharField(choices=[('CIC', 'Cichlids'), ('RBF', 'Rainbowfish'), ('KLF', 'Killifish'), ('CHA', 'Characins'), ('CAT', 'Catfish'), ('LVB', 'Livebearers'), ('CYP', 'Cyprinids'), ('ANA', 'Anabantids'), ('LCH', 'Loaches'), ('OTH', 'All Others')], default='CIC', max_length=3),
        ),
        migrations.CreateModel(
            name='BapSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('APRV', 'Approved'), ('DECL', 'Declined'), ('RESU', 'Resubmitted'), ('CLSD', 'Closed')], default='OPEN', max_length=4)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('aquarist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aquarist_bap_submissions', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_bap_submissions', to='species.aquaristclub')),
                ('speciesInstance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='species.speciesinstance')),
            ],
        ),
    ]
