# Generated by Django 5.0.1 on 2024-02-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0005_alter_species_options_species_species_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='species',
            name='species_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='speciesinstance',
            name='instance_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
