# Generated by Django 5.1.6 on 2025-06-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0005_user_is_admin_speciesinstancelabel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name'], 'verbose_name_plural': 'Species'},
        ),
        migrations.AddField(
            model_name='speciesinstance',
            name='cares_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.CharField(choices=[('CIC', 'Cichlids'), ('RBF', 'Rainbowfish'), ('KLF', 'Killifish'), ('CHA', 'Characins'), ('CAT', 'Catfish'), ('LVB', 'Livebearers'), ('CYP', 'Cyprinids'), ('ANA', 'Anabantids'), ('LCH', 'Loaches'), ('OTH', 'All Others')], default='CIC', max_length=3),
        ),
    ]
