# Generated by Django 5.0.1 on 2024-02-26 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0006_image_alter_species_species_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesinstance',
            name='currently_keeping_species',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='speciesinstance',
            name='approx_date_acquired',
            field=models.DateField(default=datetime.date.today, verbose_name='Year Acquired'),
        ),
    ]
