# Generated by Django 5.1.6 on 2025-06-26 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0006_alter_species_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='cares_category',
            field=models.CharField(choices=[('RIC', 'Adrianichthyidae (Ricefish)'), ('ANA', 'Anabantidae (Climbing Gouramies)'), ('EKF', 'Aphaniidae (Eurasian Killifish)'), ('MKF', 'Bedotiidae (Madagascan Killifish)'), ('OKF', 'Killifish (Other Killifish)'), ('CHA', 'Characidae (Tetras)'), ('CIC', 'Cichlidae (Cichlids)'), ('LCH', 'Cobitidae (Loaches)'), ('CYP', 'Cyprinidae (Minnows and Carps)'), ('PUP', 'Cyprinodontidae (Pupfish)'), ('GOB', 'Gobiidae (Gobies)'), ('GOO', 'Goodeidae (Splitfins)'), ('LOR', 'Loricariidae (Armoured Catfish)'), ('RBF', 'Melanotaeniidae (Rainbowfish)'), ('SQU', 'Mochokidae (Squeakers)'), ('TCA', 'Nothobranchiidae (Toothcarps)'), ('LVB', 'Poeciliidae (Livebearers)'), ('BLE', 'Pseudomugilidae (Blue Eyes)'), ('RIV', 'Rivulidae (Rivulus)'), ('VLC', 'Valenciidae (Valencias)'), ('UDF', 'Undefined')], default='UDF', max_length=3),
        ),
        migrations.AddField(
            model_name='species',
            name='iucn_status',
            field=models.CharField(choices=[('UD', 'Undefined'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('EW', 'Extict in the Wild')], default='UD', max_length=2),
        ),
        migrations.AlterField(
            model_name='species',
            name='cares_status',
            field=models.CharField(choices=[('NOTC', 'Undefined'), ('NEAR', 'Near Threatened'), ('VULN', 'Vulnerable'), ('ENDA', 'Endangered'), ('CEND', 'Critically Endangered'), ('EXCT', 'Extict in the Wild')], default='NOTC', max_length=4),
        ),
        migrations.CreateModel(
            name='CaresRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('APRV', 'Approved'), ('DECL', 'Declined'), ('RESU', 'Resubmitted'), ('CLSD', 'Closed')], default='OPEN', max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_registrations', to=settings.AUTH_USER_MODEL)),
                ('aquarist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aquarist_registrations', to=settings.AUTH_USER_MODEL)),
                ('speciesInstance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='species.speciesinstance')),
            ],
        ),
    ]
