# Generated by Django 5.2.7 on 2025-11-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0006_bap_feature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciesinstance',
            old_name='instance_image',
            new_name='aquarist_species_image',
        ),
        migrations.RenameField(
            model_name='speciesinstance',
            old_name='cares_validated',
            new_name='cares_registered',
        ),        
        migrations.AddField(
            model_name='speciesinstance',
            name='aquarist_species_video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='speciesinstancelogentry',
            name='log_entry_video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='speciesmaintenancelogentry',
            name='log_entry_video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='speciesinstance',
            name='aquarist_species_video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='speciesinstancelogentry',
            name='log_entry_video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.CharField(choices=[('CIC', 'Cichlids'), ('RBF', 'Rainbowfish'), ('KLF', 'Killifish'), ('CHA', 'Characins'), ('CAT', 'Catfish'), ('LVB', 'Livebearers'), ('CYP', 'Cyprinids'), ('ANA', 'Anabantids'), ('LCH', 'Loaches'), ('INV', 'Invertebrates'), ('OTH', 'All Others')], default='CIC', max_length=3),
        ),
        migrations.AlterField(
            model_name='species',
            name='global_region',
            field=models.CharField(choices=[('SAM', 'South America'), ('CAM', 'Central America'), ('NAM', 'North America'), ('AFR', 'Africa'), ('SEA', 'Southeast Asia'), ('AUS', 'Australia'), ('EUR', 'Europe'), ('OTH', 'Other Region')], default='AFR', max_length=3),
        ),
        migrations.AlterField(
            model_name='speciesreferencelink',
            name='reference_url',
            field=models.URLField(max_length=500),
        ),
    ]
