# Generated by Django 5.1.6 on 2025-07-11 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0006_alter_species_options_aquaristclub_bap_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaristclub',
            name='bap_admins',
            field=models.ManyToManyField(related_name='user_bap_club_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='bap_guidelines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciesinstance',
            name='young_available_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
