# Generated by Django 5.0.1 on 2024-03-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0007_speciesinstance_currently_keeping_species_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
