# Generated by Django 5.2.9 on 2026-01-12 12:31

import django.core.validators
import species.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0007_video_url_feature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciesinstance',
            name='acquired_from',
        ),
        migrations.AddField(
            model_name='speciesinstancelabel',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aquaristclub',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aquaristclub',
            name='bap_guidelines',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aquaristclub',
            name='bap_notes_template',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aquaristclub',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='bapsubmission',
            name='admin_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bapsubmission',
            name='breeder_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bapsubmission',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='alt_name',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='species',
            name='common_name',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='local_distribution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='species',
            name='photo_credit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='speciesinstance',
            name='aquarist_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='speciesinstance',
            name='aquarist_species_video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='speciesinstance',
            name='collection_point',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='speciesinstance',
            name='fry_rearing_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='speciesinstance',
            name='spawning_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='speciesinstance',
            name='unique_traits',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='speciesinstance',
            name='year_acquired',
            field=models.IntegerField(blank=True, default=species.models.get_cur_year, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='speciesinstancelogentry',
            name='log_entry_video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='speciesmaintenancelog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='speciesmaintenancelogentry',
            name='log_entry_video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
