# Generated by Django 5.1.6 on 2025-07-14 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0007_aquaristclub_bap_admins_aquaristclub_bap_guidelines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bapsubmission',
            name='year',
            field=models.IntegerField(default=2025, help_text='Year only (YYYY)', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='speciesinstance',
            name='year_acquired',
            field=models.IntegerField(blank=True, default=2025, help_text='Year only (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
