# Generated by Django 5.1.6 on 2025-06-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0007_species_cares_category_species_iucn_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caresregistration',
            name='approver_group',
            field=models.CharField(choices=[('UNA', 'Unassigned'), ('CIC', 'sme_cares_cichlids'), ('LIV', 'sme_cares_livebearers'), ('GOO', 'sme_cares_goodeids'), ('BLU', 'sme_cares_blueeyes'), ('ANA', 'sme_cares_anabantids'), ('KIL', 'sme_cares_killifish')], default='UNA', max_length=4),
        ),
    ]
