# Generated by Django 5.2.9 on 2026-02-25 18:00

import django.core.validators
import django.db.models.deletion
import species.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0008_add_lastupdated_to_speciesinstancelabel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name'], 'verbose_name': 'Species Profile'},
        ),
        migrations.AlterModelOptions(
            name='speciesinstance',
            options={'ordering': ['-lastUpdated', '-created'], 'verbose_name': 'Aquarist Species', 'verbose_name_plural': 'Aquarist Species'},
        ),
        migrations.RemoveField(
            model_name='aquaristclub',
            name='club_admins',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='cares_status',
            new_name='cares_classification',
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='is_bap_club',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='is_cares_club',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aquaristclubmember',
            name='is_cares_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bapleaderboard',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='species',
            name='cares_family',
            field=models.CharField(choices=[('RIC', 'Adrianichthyidae (Ricefish)'), ('ANA', 'Anabantidae (Climbing Gouramies)'), ('EKF', 'Aphaniidae (Eurasian Killifish)'), ('MKF', 'Bedotiidae (Madagascan Killifish)'), ('OKF', 'Killifish (Other Killifish)'), ('CHA', 'Characidae (Tetras)'), ('CIC', 'Cichlidae (Cichlids)'), ('LCH', 'Cobitidae (Loaches)'), ('CYP', 'Cyprinidae (Minnows and Carps)'), ('PUP', 'Cyprinodontidae (Pupfish)'), ('GOB', 'Gobiidae (Gobies)'), ('GOO', 'Goodeidae (Splitfins)'), ('LOR', 'Loricariidae (Armoured Catfish)'), ('RBF', 'Melanotaeniidae (Rainbowfish)'), ('SQU', 'Mochokidae (Squeakers)'), ('TCA', 'Nothobranchiidae (Toothcarps)'), ('LVB', 'Poeciliidae (Livebearers)'), ('BLE', 'Pseudomugilidae (Blue Eyes)'), ('RIV', 'Rivulidae (Rivulus)'), ('VLC', 'Valenciidae (Valencias)'), ('UDF', 'Undefined')], default='UDF', max_length=3),
        ),
        migrations.AddField(
            model_name='species',
            name='iucn_red_list',
            field=models.CharField(choices=[('UN', 'Undefined'), ('NE', 'Not Evaluated'), ('DD', 'Data Deficient'), ('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('EX', 'Extinct in the Wild'), ('EW', 'Extinct in the Wild')], default='UN', max_length=2),
        ),
        migrations.AddField(
            model_name='speciesinstance',
            name='acquired_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_species_instances', to='species.speciesinstance'),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook Profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram Profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube Channel'),
        ),        
        migrations.AddField(
            model_name='user',
            name='is_proxy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_species_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='prefer_tile_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='global_region',
            field=models.CharField(choices=[('SAM', 'South America'), ('CAM', 'Central America'), ('NAM', 'North America'), ('AFR', 'Africa'), ('SEA', 'Southeast Asia'), ('AUS', 'Oceania'), ('EUR', 'Europe'), ('OTH', 'Other Region')], default='AFR', max_length=3),
        ),
        migrations.CreateModel(
            name='CaresApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('specialty', models.CharField(choices=[('RIC', 'Adrianichthyidae (Ricefish)'), ('ANA', 'Anabantidae (Climbing Gouramies)'), ('EKF', 'Aphaniidae (Eurasian Killifish)'), ('MKF', 'Bedotiidae (Madagascan Killifish)'), ('OKF', 'Killifish (Other Killifish)'), ('CHA', 'Characidae (Tetras)'), ('CIC', 'Cichlidae (Cichlids)'), ('LCH', 'Cobitidae (Loaches)'), ('CYP', 'Cyprinidae (Minnows and Carps)'), ('PUP', 'Cyprinodontidae (Pupfish)'), ('GOB', 'Gobiidae (Gobies)'), ('GOO', 'Goodeidae (Splitfins)'), ('LOR', 'Loricariidae (Armoured Catfish)'), ('RBF', 'Melanotaeniidae (Rainbowfish)'), ('SQU', 'Mochokidae (Squeakers)'), ('TCA', 'Nothobranchiidae (Toothcarps)'), ('LVB', 'Poeciliidae (Livebearers)'), ('BLE', 'Pseudomugilidae (Blue Eyes)'), ('RIV', 'Rivulidae (Rivulus)'), ('VLC', 'Valenciidae (Valencias)'), ('UDF', 'Undefined')], default='UDF', max_length=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cares_approvers', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cares_updaters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaresRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('aquarist_name', models.CharField(default='', max_length=240)),
                ('aquarist_email', models.EmailField(max_length=50, null=True)),
                ('collection_location', models.CharField(blank=True, max_length=200)),
                ('species_source', models.TextField(default='')),
                ('year_acquired', models.IntegerField(blank=True, default=species.models.get_cur_year, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('verification_photo', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('species_has_spawned', models.BooleanField(default=False)),
                ('young_available', models.BooleanField(default=False)),
                ('offspring_shared', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('approver_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('APRV', 'Approved'), ('DECL', 'Declined'), ('RESU', 'Resubmitted'), ('EXPI', 'Expired'), ('CLSD', 'Closed')], default='OPEN', max_length=4)),
                ('last_report_date', models.DateField(blank=True, null=True)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('affiliate_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_cares_registrations', to='species.aquaristclub')),
                ('cares_approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_cares_registrations', to='species.caresapprover')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cares_registration_last_updates', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_registrations', to='species.species')),
            ],
        ),
    ]
