# Generated by Django 5.1.6 on 2025-07-14 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0008_bapsubmission_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bapsubmission',
            name='points',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='bapsubmission',
            name='year',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='speciesinstance',
            name='year_acquired',
            field=models.IntegerField(blank=True, default=2025, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
