# Generated by Django 5.0.1 on 2024-03-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0008_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='category',
            field=models.CharField(choices=[('CIC', 'Cichlids'), ('RBF', 'Rainbowfish'), ('KLF', 'Killifish'), ('CHA', 'Characins (Tetras)'), ('CAT', 'Catfish'), ('LVB', 'Livebearers'), ('CYP', 'Cyprinids (Carps, Barbs, Danios, Minnows)'), ('ANA', 'Anabatids (Gouramis, Bettas)'), ('LCH', 'Loaches'), ('OTH', 'All Others')], default='CIC', max_length=3),
        ),
    ]
