# Generated by Django 5.2.9 on 2026-01-13 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0008_add_lastupdated_to_speciesinstancelabel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaristclubmember',
            name='is_cares_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bapleaderboard',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='species',
            name='cares_family',
            field=models.CharField(choices=[('RIC', 'Adrianichthyidae (Ricefish)'), ('ANA', 'Anabantidae (Climbing Gouramies)'), ('EKF', 'Aphaniidae (Eurasian Killifish)'), ('MKF', 'Bedotiidae (Madagascan Killifish)'), ('OKF', 'Killifish (Other Killifish)'), ('CHA', 'Characidae (Tetras)'), ('CIC', 'Cichlidae (Cichlids)'), ('LCH', 'Cobitidae (Loaches)'), ('CYP', 'Cyprinidae (Minnows and Carps)'), ('PUP', 'Cyprinodontidae (Pupfish)'), ('GOB', 'Gobiidae (Gobies)'), ('GOO', 'Goodeidae (Splitfins)'), ('LOR', 'Loricariidae (Armoured Catfish)'), ('RBF', 'Melanotaeniidae (Rainbowfish)'), ('SQU', 'Mochokidae (Squeakers)'), ('TCA', 'Nothobranchiidae (Toothcarps)'), ('LVB', 'Poeciliidae (Livebearers)'), ('BLE', 'Pseudomugilidae (Blue Eyes)'), ('RIV', 'Rivulidae (Rivulus)'), ('VLC', 'Valenciidae (Valencias)'), ('UDF', 'Undefined')], default='UDF', max_length=3),
        ),
        migrations.AddField(
            model_name='species',
            name='iucn_red_list',
            field=models.CharField(choices=[('UN', 'Undefined'), ('NE', 'Not Evaluated'), ('DD', 'Data Deficient'), ('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('EX', 'Extinct in the Wild'), ('EW', 'Extinct in the Wild')], default='UN', max_length=2),
        ),
        migrations.AddField(
            model_name='speciesinstance',
            name='acquired_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_species_instances', to='species.speciesinstance'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_proxy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='cares_status',
            field=models.CharField(choices=[('NOTC', 'Undefined'), ('NEAR', 'Near Threatened'), ('VULN', 'Vulnerable'), ('ENDA', 'Endangered'), ('CEND', 'Critically Endangered'), ('EXCT', 'Extinct in the Wild')], default='NOTC', max_length=4),
        ),
        migrations.CreateModel(
            name='CaresApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('specialty', models.CharField(choices=[('RIC', 'Adrianichthyidae (Ricefish)'), ('ANA', 'Anabantidae (Climbing Gouramies)'), ('EKF', 'Aphaniidae (Eurasian Killifish)'), ('MKF', 'Bedotiidae (Madagascan Killifish)'), ('OKF', 'Killifish (Other Killifish)'), ('CHA', 'Characidae (Tetras)'), ('CIC', 'Cichlidae (Cichlids)'), ('LCH', 'Cobitidae (Loaches)'), ('CYP', 'Cyprinidae (Minnows and Carps)'), ('PUP', 'Cyprinodontidae (Pupfish)'), ('GOB', 'Gobiidae (Gobies)'), ('GOO', 'Goodeidae (Splitfins)'), ('LOR', 'Loricariidae (Armoured Catfish)'), ('RBF', 'Melanotaeniidae (Rainbowfish)'), ('SQU', 'Mochokidae (Squeakers)'), ('TCA', 'Nothobranchiidae (Toothcarps)'), ('LVB', 'Poeciliidae (Livebearers)'), ('BLE', 'Pseudomugilidae (Blue Eyes)'), ('RIV', 'Rivulidae (Rivulus)'), ('VLC', 'Valenciidae (Valencias)'), ('UDF', 'Undefined')], default='UDF', max_length=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cares_approvers', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cares_updaters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaresRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('verification_photo', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('acquired_species_source', models.TextField()),
                ('acquired_species_timing', models.TextField()),
                ('species_has_spawned', models.BooleanField(default=False)),
                ('offspring_distributed', models.BooleanField(default=False)),
                ('approver_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('APRV', 'Approved'), ('DECL', 'Declined'), ('RESU', 'Resubmitted'), ('EXPI', 'Expired'), ('CLSD', 'Closed')], default='OPEN', max_length=4)),
                ('last_report_date', models.DateField(blank=True, null=True)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('affiliate_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_cares_registrations', to='species.aquaristclub')),
                ('aquarist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aquarist_cares_registrations', to=settings.AUTH_USER_MODEL)),
                ('cares_approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_cares_registrations', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cares_registration_last_updates', to=settings.AUTH_USER_MODEL)),
                ('speciesInstance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='species.speciesinstance')),
            ],
        ),
    ]
