# Generated by Django 5.2.9 on 2026-01-18 11:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0009_cares_feature_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name'], 'verbose_name': 'Species Profile'},
        ),
        migrations.AlterModelOptions(
            name='speciesinstance',
            options={'ordering': ['-lastUpdated', '-created'], 'verbose_name': 'Aquarist Species', 'verbose_name_plural': 'Aquarist Species'},
        ),
        migrations.RemoveField(
            model_name='caresregistration',
            name='offspring_distributed',
        ),
        migrations.RemoveField(
            model_name='caresregistration',
            name='speciesInstance',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='cares_status',
            new_name='cares_classification',
        ),
        migrations.AddField(
            model_name='caresregistration',
            name='offspring_shared',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='caresregistration',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_registrations', to='species.species'),
        ),
    ]
