# Generated by Django 5.1.6 on 2025-07-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0009_bapsubmission_points_alter_bapsubmission_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquaristclubmember',
            name='membership_requested',
        ),
        migrations.AddField(
            model_name='aquaristclubmember',
            name='bap_participant',
            field=models.BooleanField(default=False),
        ),
    ]
