# Generated by Django 5.2.9 on 2026-02-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0009_enable_cares_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='species_instance_count',
        ),
        migrations.AlterField(
            model_name='species',
            name='cares_classification',
            field=models.CharField(choices=[('NOTC', 'Undefined'), ('NEAR', 'Near Threatened'), ('VULN', 'Vulnerable'), ('ENDA', 'Endangered'), ('CEND', 'Critically Endangered'), ('EXCT', 'Extinct in the Wild')], default='NOTC', max_length=4),
        ),
        migrations.AlterField(
            model_name='species',
            name='iucn_red_list',
            field=models.CharField(choices=[('UN', 'Undefined'), ('NE', 'Not Evaluated'), ('DD', 'Data Deficient'), ('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('EW', 'Extinct in the Wild'), ('EX', 'Extinct')], default='UN', max_length=2),
        ),
    ]
