# Generated by Django 5.0.1 on 2024-03-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0010_alter_species_species_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importarchive',
            name='name',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='importarchive',
            name='import_status',
            field=models.CharField(choices=[('PEND', 'Pending'), ('PART', 'Incomplete Species List Import'), ('FULL', 'Complete Speces List Import'), ('FAIL', 'Import Failure')], default='PEND', max_length=4),
        ),
    ]
