# Generated by Django 5.2.9 on 2026-01-19 12:01

import django.core.validators
import species.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0010_alter_cares_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caresregistration',
            name='acquired_species_source',
        ),
        migrations.RemoveField(
            model_name='caresregistration',
            name='acquired_species_timing',
        ),
        migrations.AddField(
            model_name='caresregistration',
            name='collection_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='caresregistration',
            name='species_source',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='caresregistration',
            name='year_acquired',
            field=models.IntegerField(blank=True, default=species.models.get_cur_year, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
