# Generated by Django 5.2.9 on 2026-04-02 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0010_revise_species_enums_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='cares_assessment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='iucn_assessment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caresapprover',
            name='specialty',
            field=models.CharField(choices=[('RICE', 'Adrianichthyidae - Ricefish'), ('ANAB', 'Anabantidae - Climbing Gouramies'), ('EUKIL', 'Aphaniidae - Eurasian Killifish'), ('SAKIL', 'Aplocheilidae - SE Asia Killifish'), ('MRAIN', 'Bedotiidae - Madagascar Rainbowfish'), ('CHAR', 'Characidae - Tetras'), ('ASCIC', 'Cichlidae - Asia'), ('CACIC', 'Cichlidae - Central America'), ('EACIC', 'Cichlidae - East Africa'), ('LMCIC', 'Cichlidae - Lake Malawi'), ('LTCIC', 'Cichlidae - Lake Tanganyika'), ('LVCIC', 'Cichlidae - Lake Victoria'), ('MACIC', 'Cichlidae - Madagascar'), ('NACIC', 'Cichlidae - North Africa'), ('SACIC', 'Cichlidae - South Africa'), ('WACIC', 'Cichlidae - West Africa'), ('COBI', 'Cobitidae - True Loaches'), ('CYPR', 'Cyprinidae - Minnows and Carps'), ('CYKIL', 'Cyprinodontidae - Small Killifish (Pupfish)'), ('FUND', 'Fundulidae - North American Killifish'), ('GOBI', 'Gobiidae - Gobies'), ('GOOD', 'Goodeidae - Splitfin Livebearers'), ('LORI', 'Loricariidae - Armoured Catfish'), ('RAIN', 'Melanotaeniidae - Oceania Rainbowfish'), ('SQUE', 'Mochokidae - Upside-down Catfish (Squeakers)'), ('NOTH', 'Nothobranchiidae - African Killifish'), ('BETT', 'Osphronemidae - Bettas'), ('POEC', 'Poeciliidae - Livebearers'), ('PSMU', 'Pseudomugilidae - Blue-eyed Rainbowfish'), ('RIVU', 'Rivulidae - South American Killifish'), ('VALE', 'Valenciidae - Mediteranean Killifish'), ('UDF', 'Undefined')], default='UDF', max_length=5),
        ),
        migrations.AlterField(
            model_name='species',
            name='cares_classification',
            field=models.CharField(choices=[('NOTC', 'Undefined'), ('NEAR', 'Near Threatened'), ('VULN', 'Vulnerable'), ('ENDA', 'Endangered'), ('CEND', 'Critically Endangered'), ('EXCT', 'Extinct in the Wild'), ('CNT', 'CARES Extinct in the Wild'), ('CVU', 'CARES Vulnerable'), ('CEN', 'CARES Endangered'), ('CCR', 'CARES Critically Endangered'), ('CEW', 'CARES Extinct in the Wild')], default='NOTC', max_length=4),
        ),
        migrations.AlterField(
            model_name='species',
            name='cares_family',
            field=models.CharField(choices=[('RICE', 'Adrianichthyidae - Ricefish'), ('ANAB', 'Anabantidae - Climbing Gouramies'), ('EUKIL', 'Aphaniidae - Eurasian Killifish'), ('SAKIL', 'Aplocheilidae - SE Asia Killifish'), ('MRAIN', 'Bedotiidae - Madagascar Rainbowfish'), ('CHAR', 'Characidae - Tetras'), ('ASCIC', 'Cichlidae - Asia'), ('CACIC', 'Cichlidae - Central America'), ('EACIC', 'Cichlidae - East Africa'), ('LMCIC', 'Cichlidae - Lake Malawi'), ('LTCIC', 'Cichlidae - Lake Tanganyika'), ('LVCIC', 'Cichlidae - Lake Victoria'), ('MACIC', 'Cichlidae - Madagascar'), ('NACIC', 'Cichlidae - North Africa'), ('SACIC', 'Cichlidae - South Africa'), ('WACIC', 'Cichlidae - West Africa'), ('COBI', 'Cobitidae - True Loaches'), ('CYPR', 'Cyprinidae - Minnows and Carps'), ('CYKIL', 'Cyprinodontidae - Small Killifish (Pupfish)'), ('FUND', 'Fundulidae - North American Killifish'), ('GOBI', 'Gobiidae - Gobies'), ('GOOD', 'Goodeidae - Splitfin Livebearers'), ('LORI', 'Loricariidae - Armoured Catfish'), ('RAIN', 'Melanotaeniidae - Oceania Rainbowfish'), ('SQUE', 'Mochokidae - Upside-down Catfish (Squeakers)'), ('NOTH', 'Nothobranchiidae - African Killifish'), ('BETT', 'Osphronemidae - Bettas'), ('POEC', 'Poeciliidae - Livebearers'), ('PSMU', 'Pseudomugilidae - Blue-eyed Rainbowfish'), ('RIVU', 'Rivulidae - South American Killifish'), ('VALE', 'Valenciidae - Mediteranean Killifish'), ('UDF', 'Undefined')], default='UDF', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SpeciesImportStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_row_number', models.IntegerField()),
                ('action', models.CharField(choices=[('NEW', 'New species to add'), ('UPDATE', 'Update existing species'), ('SKIP', 'Skip - no changes'), ('CONFLICT', 'Requires review')], max_length=10)),
                ('new_name', models.CharField(max_length=240)),
                ('new_alt_name', models.CharField(blank=True, max_length=240)),
                ('new_common_name', models.CharField(blank=True, max_length=240)),
                ('new_description', models.TextField(blank=True)),
                ('new_category', models.CharField(blank=True, max_length=3)),
                ('new_global_region', models.CharField(blank=True, max_length=3)),
                ('new_local_distribution', models.CharField(blank=True, max_length=200)),
                ('new_cares_family', models.CharField(blank=True, max_length=5)),
                ('new_cares_classification', models.CharField(blank=True, max_length=4)),
                ('new_cares_assessment_date', models.CharField(blank=True, max_length=10)),
                ('new_iucn_red_list', models.CharField(blank=True, max_length=2)),
                ('new_iucn_assessment_date', models.CharField(blank=True, max_length=10)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('OVERRIDE', 'Approved with Override'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('changed_fields', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('existing_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_staging', to='species.species')),
                ('import_archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_records', to='species.importarchive')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Species Import Staging',
                'verbose_name_plural': 'Species Import Staging',
                'ordering': ['import_row_number'],
            },
        ),
    ]
