# Generated by Django 5.1.6 on 2025-07-16 08:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0010_remove_aquaristclubmember_membership_requested_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BapLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('year', models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('aquarist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aquarist_bap_leaderboards', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_bap_leaderboards', to='species.aquaristclub')),
            ],
        ),
    ]
