# Generated by Django 5.2.9 on 2026-03-24 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0010_revise_species_enums_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesImportStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_row_number', models.IntegerField()),
                ('action', models.CharField(choices=[('NEW', 'New species to add'), ('UPDATE', 'Update existing species'), ('SKIP', 'Skip - no changes'), ('CONFLICT', 'Requires review')], max_length=10)),
                ('new_name', models.CharField(max_length=240)),
                ('new_alt_name', models.CharField(blank=True, max_length=240)),
                ('new_common_name', models.CharField(blank=True, max_length=240)),
                ('new_description', models.TextField(blank=True)),
                ('new_species_image', models.CharField(blank=True, max_length=500)),
                ('new_photo_credit', models.CharField(blank=True, max_length=200)),
                ('new_category', models.CharField(blank=True, max_length=3)),
                ('new_global_region', models.CharField(blank=True, max_length=3)),
                ('new_local_distribution', models.CharField(blank=True, max_length=200)),
                ('new_cares_family', models.CharField(blank=True, max_length=3)),
                ('new_iucn_red_list', models.CharField(blank=True, max_length=2)),
                ('new_cares_classification', models.CharField(blank=True, max_length=4)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('changed_fields', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('existing_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_staging', to='species.species')),
                ('import_archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_records', to='species.importarchive')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Species Import Staging',
                'verbose_name_plural': 'Species Import Staging',
                'ordering': ['import_row_number'],
            },
        ),
    ]
