# Generated by Django 5.2.9 on 2026-01-20 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0011_alter_cares_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caresregistration',
            name='cares_approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_cares_registrations', to='species.caresapprover'),
        ),
    ]
