# Generated by Django 5.1.6 on 2025-07-16 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0011_bapleaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='bapleaderboard',
            name='cares_species_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='bapleaderboard',
            name='species_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
