# Generated by Django 5.0.1 on 2024-03-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0011_importarchive_name_alter_importarchive_import_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importarchive',
            name='import_status',
            field=models.CharField(choices=[('PEND', 'Pending'), ('PART', 'Partial Import'), ('FULL', 'Full Import'), ('FAIL', 'Import Failure')], default='PEND', max_length=4),
        ),
        migrations.AlterField(
            model_name='importarchive',
            name='name',
            field=models.CharField(max_length=240),
        ),
    ]
