# Generated by Django 5.2.9 on 2026-03-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0011_add_species_import_staging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciesimportstaging',
            name='new_photo_credit',
        ),
        migrations.RemoveField(
            model_name='speciesimportstaging',
            name='new_species_image',
        ),
    ]
