# Generated by Django 5.2.9 on 2026-04-11 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0011_species_staged_import_and_cares_assessment_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='caresregistration',
            name='asn_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='cares_classification',
            field=models.CharField(choices=[('NOTC', 'Undefined'), ('NEAR', 'Near Threatened'), ('VULN', 'Vulnerable'), ('ENDA', 'Endangered'), ('CEND', 'Critically Endangered'), ('EXCT', 'Extinct in the Wild'), ('CNT', 'Near Threatened'), ('CVU', 'Vulnerable'), ('CEN', 'Endangered'), ('CCR', 'Critically Endangered'), ('CEW', 'Extinct in the Wild')], default='NOTC', max_length=4),
        ),
        migrations.AlterField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='species',
            name='global_region',
            field=models.CharField(choices=[('SAM', 'South America'), ('CAM', 'Central America'), ('NAM', 'North America'), ('AFR', 'Africa'), ('SEA', 'Asia'), ('AUS', 'Oceania'), ('EUR', 'Europe'), ('OTH', 'Other Region')], default='AFR', max_length=3),
        ),
        migrations.CreateModel(
            name='SpeciesFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('comment', models.TextField(max_length=2500)),
                ('species_image', models.ImageField(blank=True, null=True, upload_to='feedback/%Y/%m/%d')),
                ('species_photo_credit', models.CharField(blank=True, max_length=200)),
                ('approved', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedback', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_submissions', to='species.species')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Species Feedback',
                'verbose_name_plural': 'Species Feedback',
                'ordering': ['-created'],
            },
        ),
    ]
