# Generated by Django 5.2.9 on 2026-04-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0012_add_species_feedback_and_description_limit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='speciesfeedback',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='speciesfeedback',
            name='comment',
            field=models.TextField(max_length=2500),
        ),
    ]
