# Generated by Django 5.2.9 on 2026-01-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0012_alter_caresregistration_cares_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaristclub',
            name='is_bap_club',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='is_cares_club',
            field=models.BooleanField(default=False),
        ),
    ]
