# Generated by Django 5.1.6 on 2025-07-30 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0012_bapleaderboard_cares_species_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquaristclub',
            name='bap_admins',
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='bap_notes_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aquaristclub',
            name='club_admins',
            field=models.ManyToManyField(related_name='admin_aquarist_clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
