# Generated by Django 5.2.9 on 2026-04-20 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0012_species_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaristclub',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='caresregistration',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='species',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='caresregistration',
            name='affiliate_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_cares_registrations', to='species.aquaristclub'),
        ),
        migrations.AlterField(
            model_name='species',
            name='cares_classification',
            field=models.CharField(choices=[('NOTC', 'Undefined'), ('CNT', 'Near Threatened'), ('CVU', 'Vulnerable'), ('CEN', 'Endangered'), ('CCR', 'Critically Endangered'), ('CEW', 'Extinct in the Wild')], default='NOTC', max_length=4),
        ),
        migrations.AlterField(
            model_name='speciesinstance',
            name='genetic_traits',
            field=models.CharField(choices=[('AS', 'Aquarium Strain'), ('WC', 'F0 Wild Caught'), ('F1', 'F1 First Generation'), ('F2', 'F2 Second Generation'), ('FX', 'FX 3rd or more Generation'), ('OT', 'Other')], default='AS', max_length=2),
        ),
    ]
