# Generated by Django 5.0.1 on 2024-04-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0012_alter_importarchive_import_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='cares_status',
            field=models.CharField(choices=[('NOTC', 'Not a CARES Species'), ('NEAR', 'Near Threatened'), ('VULN', 'Vulnerable'), ('ENDA', 'Endangered'), ('CEND', 'Critically Endangered'), ('EXCT', 'Extict in the Wild')], default='NOTC', max_length=4),
        ),
    ]
