# Generated by Django 5.1.6 on 2025-07-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0013_remove_aquaristclub_bap_admins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaristclub',
            name='bap_config_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
