# Generated by Django 5.2.9 on 2026-05-21 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0013_page_metrics_reg_exchange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='manage_collection_locations',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='caresregistration',
            name='cares_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_cares_registrations', to='species.caresapprover'),
        ),
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.CharField(choices=[('CIC', 'Cichlids'), ('RBF', 'Rainbowfish'), ('KLF', 'Killifish'), ('CHA', 'Characins'), ('CAT', 'Catfish'), ('LVB', 'Livebearers'), ('CYP', 'Cyprinids'), ('ANA', 'Anabantids'), ('LCH', 'Loaches'), ('INV', 'Invertebrates'), ('OTH', 'All Others'), ('UDF', 'Undefined')], default='CIC', max_length=3),
        ),
        migrations.AlterField(
            model_name='species',
            name='global_region',
            field=models.CharField(choices=[('SAM', 'South America'), ('CAM', 'Central America'), ('NAM', 'North America'), ('AFR', 'Africa'), ('SEA', 'Asia'), ('AUS', 'Oceania'), ('EUR', 'Europe'), ('OTH', 'Other Region'), ('UDF', 'Undefined')], default='AFR', max_length=3),
        ),
        migrations.CreateModel(
            name='SpeciesAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('category', models.CharField(choices=[('CIC', 'Cichlids'), ('RBF', 'Rainbowfish'), ('KLF', 'Killifish'), ('CHA', 'Characins'), ('CAT', 'Catfish'), ('LVB', 'Livebearers'), ('CYP', 'Cyprinids'), ('ANA', 'Anabantids'), ('LCH', 'Loaches'), ('INV', 'Invertebrates'), ('OTH', 'All Others'), ('UDF', 'Undefined')], default='UDF', max_length=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_admin_updaters', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_admins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpeciesCollectionLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_locations', to='species.species')),
            ],
            options={
                'verbose_name': 'Collection Location',
                'verbose_name_plural': 'Collection Locations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='speciesinstance',
            name='collection_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_instances', to='species.speciescollectionlocation'),
        ),
        migrations.RemoveField(
            model_name='caresregistration',
            name='collection_location',
        ),
        migrations.AddField(
            model_name='caresregistration',
            name='collection_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cares_registrations', to='species.speciescollectionlocation'),
        ),
    ]
