# Generated by Django 5.2.9 on 2026-04-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0013_species_external_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('USER', 'Aquarist'), ('SPEC', 'Species'), ('SPIN', 'Aquarist Species'), ('SPML', 'Species Maintenance Log'), ('AQCL', 'Aquarist Club'), ('BAPL', 'BAP Leaderboard')], max_length=4)),
                ('object_id', models.IntegerField()),
                ('visitor_type', models.CharField(choices=[('AN', 'Anonymous'), ('AU', 'Authenticated')], max_length=2)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Page View Count',
                'verbose_name_plural': 'Page View Counts',
            },
        ),
        migrations.CreateModel(
            name='PageViewMonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('USER', 'Aquarist'), ('SPEC', 'Species'), ('SPIN', 'Aquarist Species'), ('SPML', 'Species Maintenance Log'), ('AQCL', 'Aquarist Club'), ('BAPL', 'BAP Leaderboard')], max_length=4)),
                ('object_id', models.IntegerField()),
                ('visitor_type', models.CharField(choices=[('AN', 'Anonymous'), ('AU', 'Authenticated')], max_length=2)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Page View Monthly Summary',
                'verbose_name_plural': 'Page View Monthly Summaries',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.AddIndex(
            model_name='pageviewcount',
            index=models.Index(fields=['page_type', 'object_id'], name='species_pag_page_ty_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pageviewcount',
            unique_together={('page_type', 'object_id', 'visitor_type')},
        ),
        migrations.AddIndex(
            model_name='pageviewmonthlysummary',
            index=models.Index(fields=['page_type', 'object_id', 'year', 'month'], name='species_pag_page_ty_mo_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pageviewmonthlysummary',
            unique_together={('page_type', 'object_id', 'visitor_type', 'year', 'month')},
        ),
    ]
