# Generated by Django 5.2.9 on 2026-01-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0013_aquaristclub_is_bap_club_aquaristclub_is_cares_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='caresregistration',
            name='aquarist_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='caresregistration',
            name='aquarist_name',
            field=models.CharField(default='', max_length=240),
        ),        
        migrations.AddField(
            model_name='caresregistration',
            name='young_available',
            field=models.BooleanField(default=False),
        ),
    ]
