# Generated by Django 5.0.1 on 2024-04-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0013_species_cares_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='render_cares',
            field=models.BooleanField(default=False),
        ),
    ]
