# Generated by Django 5.2.9 on 2026-05-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0013_page_metrics_reg_exchange_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesCollectionLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_locations', to='species.species')),
            ],
            options={
                'verbose_name': 'Collection Location',
                'verbose_name_plural': 'Collection Locations',
                'ordering': ['name'],
            },
        ),
    ]
