# Generated by Django 5.2.9 on 2026-05-20

from django.db import migrations


def forwards(apps, schema_editor):
    SpeciesInstance = apps.get_model('species', 'SpeciesInstance')
    CaresRegistration = apps.get_model('species', 'CaresRegistration')
    SpeciesCollectionLocation = apps.get_model('species', 'SpeciesCollectionLocation')

    seen = set()

    for si in SpeciesInstance.objects.exclude(collection_point__isnull=True).exclude(collection_point='').iterator():
        name = (si.collection_point or '').strip()
        if not name:
            continue
        key = (si.species_id, name.lower())
        if key in seen:
            continue
        exists = SpeciesCollectionLocation.objects.filter(species_id=si.species_id, name__iexact=name).exists()
        if not exists:
            SpeciesCollectionLocation.objects.create(species_id=si.species_id, name=name)
        seen.add(key)

    for reg in CaresRegistration.objects.exclude(collection_location__isnull=True).exclude(collection_location='').iterator():
        name = (reg.collection_location or '').strip()
        if not name or not reg.species_id:
            continue
        key = (reg.species_id, name.lower())
        if key in seen:
            continue
        exists = SpeciesCollectionLocation.objects.filter(species_id=reg.species_id, name__iexact=name).exists()
        if not exists:
            SpeciesCollectionLocation.objects.create(species_id=reg.species_id, name=name)
        seen.add(key)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0014_speciescollectionlocation'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
