# Generated by Django 5.2.9 on 2026-08-29 20:16

import django.core.validators
import django.db.models.deletion
import species.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


# Ported verbatim from 0019_backfill_bap_year_and_lifetime_totals.
def _backfill_bap_year_and_lifetime_totals(apps, schema_editor):
    AquaristClub = apps.get_model('species', 'AquaristClub')
    BapYear = apps.get_model('species', 'BapYear')
    BapSubmission = apps.get_model('species', 'BapSubmission')
    BapLeaderboard = apps.get_model('species', 'BapLeaderboard')
    BapLifetimeTotal = apps.get_model('species', 'BapLifetimeTotal')

    today = timezone.localdate()

    # 1) Initial BapYear per BAP-enabled club from legacy start/end dates
    for club in AquaristClub.objects.filter(is_bap_club=True).exclude(bap_start_date__isnull=True).exclude(bap_end_date__isnull=True):
        year_label = club.bap_end_date.year
        defaults = {
            'name': f'{year_label} BAP Year',
            'start_date': club.bap_start_date,
            'end_date': club.bap_end_date,
            'status': 'OPEN' if club.bap_end_date >= today else 'CLSD',
        }
        bap_year, _ = BapYear.objects.get_or_create(club=club, year_label=year_label, defaults=defaults)
        if bap_year.status == 'CLSD' and bap_year.closed_at is None:
            bap_year.closed_at = timezone.now()
            bap_year.save(update_fields=['closed_at'])

    # 2) Backfill submission species from speciesInstance.species and bap_year link from year label
    for sub in BapSubmission.objects.select_related('speciesInstance', 'club').all():
        update_fields = []
        if sub.species_id is None and sub.speciesInstance_id:
            si = sub.speciesInstance
            if si and si.species_id:
                sub.species_id = si.species_id
                update_fields.append('species_id')
        if sub.bap_year_id is None and sub.club_id and sub.year:
            by = BapYear.objects.filter(club_id=sub.club_id, year_label=sub.year).first()
            if by:
                sub.bap_year_id = by.id
                update_fields.append('bap_year_id')
        if update_fields:
            sub.save(update_fields=update_fields)

    # 3) Backfill leaderboard bap_year from club/year
    for lb in BapLeaderboard.objects.filter(bap_year__isnull=True).exclude(club__isnull=True):
        by = BapYear.objects.filter(club_id=lb.club_id, year_label=lb.year).first()
        if by:
            lb.bap_year_id = by.id
            lb.save(update_fields=['bap_year_id'])

    # 4) Backfill BapLifetimeTotal from approved submissions
    approved = BapSubmission.objects.filter(status='APRV').select_related('species', 'club', 'aquarist', 'bap_year').order_by('created')
    grouped = {}
    for sub in approved:
        if not sub.aquarist_id or not sub.club_id:
            continue
        key = (sub.aquarist_id, sub.club_id)
        if key not in grouped:
            grouped[key] = {
                'species_ids': set(),
                'cares_species_ids': set(),
                'points': 0,
                'first_year': None,
                'last_year': None,
            }
        bucket = grouped[key]
        if sub.species_id:
            bucket['species_ids'].add(sub.species_id)
            if getattr(sub.species, 'render_cares', False):
                bucket['cares_species_ids'].add(sub.species_id)
        bucket['points'] += sub.points or 0
        if sub.bap_year_id:
            if bucket['first_year'] is None:
                bucket['first_year'] = sub.bap_year_id
            bucket['last_year'] = sub.bap_year_id

    for (aquarist_id, club_id), bucket in grouped.items():
        BapLifetimeTotal.objects.update_or_create(
            aquarist_id=aquarist_id,
            club_id=club_id,
            defaults={
                'species_count': len(bucket['species_ids']),
                'cares_species_count': len(bucket['cares_species_ids']),
                'points': bucket['points'],
                'first_award_year_id': bucket['first_year'],
                'last_award_year_id': bucket['last_year'],
            }
        )


def _backfill_bap_year_and_lifetime_totals_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    replaces = [('species', '0015_cares_reg_synch_state_bap_improvements_and_more'), ('species', '0024_aquaristclubemailalias'), ('species', '0025_remove_aquaristclub_bap_notes_template')]

    dependencies = [
        ('species', '0014_species_manage_collection_locations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('site1_to_site2', 'Site1 → Site2 (new registrations)'), ('site2_to_site1', 'Site2 → Site1 (status updates)')], max_length=20, unique=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful sync run for this direction.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registration Sync State',
                'verbose_name_plural': 'Registration Sync States',
            },
        ),
        migrations.AddField(
            model_name='caresregistration',
            name='submitter_notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='caresapprover',
            name='specialty',
            field=models.CharField(choices=[('RICE', 'Adrianichthyidae - Ricefish'), ('ANAB', 'Anabantidae - Climbing Gouramies'), ('EUKIL', 'Aphaniidae - Eurasian Killifish'), ('SAKIL', 'Aplocheilidae - SE Asia Killifish'), ('MRAIN', 'Bedotiidae - Madagascar Rainbowfish'), ('CHAR', 'Characidae - Tetras'), ('ASCIC', 'Cichlidae - Asia'), ('CACIC', 'Cichlidae - Central America'), ('EACIC', 'Cichlidae - East Africa'), ('LMCIC', 'Cichlidae - Lake Malawi'), ('LTCIC', 'Cichlidae - Lake Tanganyika'), ('LVCIC', 'Cichlidae - Lake Victoria'), ('MACIC', 'Cichlidae - Madagascar'), ('NACIC', 'Cichlidae - North Africa'), ('SACIC', 'Cichlidae - South America'), ('WACIC', 'Cichlidae - West Africa'), ('COBI', 'Cobitidae - True Loaches'), ('CYPR', 'Cyprinidae - Minnows and Carps'), ('CYKIL', 'Cyprinodontidae - Small Killifish (Pupfish)'), ('FUND', 'Fundulidae - North American Killifish'), ('GOBI', 'Gobiidae - Gobies'), ('GOOD', 'Goodeidae - Splitfin Livebearers'), ('LORI', 'Loricariidae - Armoured Catfish'), ('RAIN', 'Melanotaeniidae - Oceania Rainbowfish'), ('SQUE', 'Mochokidae - Upside-down Catfish (Squeakers)'), ('NOTH', 'Nothobranchiidae - African Killifish'), ('BETT', 'Osphronemidae - Bettas'), ('POEC', 'Poeciliidae - Livebearers'), ('PSMU', 'Pseudomugilidae - Blue-eyed Rainbowfish'), ('RIVU', 'Rivulidae - South American Killifish'), ('VALE', 'Valenciidae - Mediteranean Killifish'), ('UDF', 'Undefined')], default='UDF', max_length=5),
        ),
        migrations.AlterField(
            model_name='caresregistration',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('APRV', 'Approved'), ('PEND', 'Pending'), ('DECL', 'Declined'), ('RESU', 'Resubmitted'), ('EXPI', 'Expired'), ('CLSD', 'Closed')], default='OPEN', max_length=4),
        ),
        migrations.AlterField(
            model_name='species',
            name='cares_family',
            field=models.CharField(choices=[('RICE', 'Adrianichthyidae - Ricefish'), ('ANAB', 'Anabantidae - Climbing Gouramies'), ('EUKIL', 'Aphaniidae - Eurasian Killifish'), ('SAKIL', 'Aplocheilidae - SE Asia Killifish'), ('MRAIN', 'Bedotiidae - Madagascar Rainbowfish'), ('CHAR', 'Characidae - Tetras'), ('ASCIC', 'Cichlidae - Asia'), ('CACIC', 'Cichlidae - Central America'), ('EACIC', 'Cichlidae - East Africa'), ('LMCIC', 'Cichlidae - Lake Malawi'), ('LTCIC', 'Cichlidae - Lake Tanganyika'), ('LVCIC', 'Cichlidae - Lake Victoria'), ('MACIC', 'Cichlidae - Madagascar'), ('NACIC', 'Cichlidae - North Africa'), ('SACIC', 'Cichlidae - South America'), ('WACIC', 'Cichlidae - West Africa'), ('COBI', 'Cobitidae - True Loaches'), ('CYPR', 'Cyprinidae - Minnows and Carps'), ('CYKIL', 'Cyprinodontidae - Small Killifish (Pupfish)'), ('FUND', 'Fundulidae - North American Killifish'), ('GOBI', 'Gobiidae - Gobies'), ('GOOD', 'Goodeidae - Splitfin Livebearers'), ('LORI', 'Loricariidae - Armoured Catfish'), ('RAIN', 'Melanotaeniidae - Oceania Rainbowfish'), ('SQUE', 'Mochokidae - Upside-down Catfish (Squeakers)'), ('NOTH', 'Nothobranchiidae - African Killifish'), ('BETT', 'Osphronemidae - Bettas'), ('POEC', 'Poeciliidae - Livebearers'), ('PSMU', 'Pseudomugilidae - Blue-eyed Rainbowfish'), ('RIVU', 'Rivulidae - South American Killifish'), ('VALE', 'Valenciidae - Mediteranean Killifish'), ('UDF', 'Undefined')], default='UDF', max_length=5),
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='next_member_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='BapImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_name', models.CharField(max_length=240)),
                ('auction_date', models.DateField(blank=True, null=True)),
                ('working_csv_file', models.FileField(blank=True, null=True, upload_to='bap_imports/working/')),
                ('status', models.CharField(choices=[('REVIEW', 'In Review'), ('PROCESSED', 'Processed')], default='REVIEW', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bap_import_batches', to='species.aquaristclub')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bap_import_batches_created', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bap_import_batches_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BAP Import Batch',
                'verbose_name_plural': 'BAP Import Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmpLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('year', models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('species_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('is_final', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmpLifetimeTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-points', '-species_count'],
            },
        ),
        migrations.CreateModel(
            name='SmpSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('maintenance_year_number', models.PositiveIntegerField(default=1)),
                ('base_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('smp_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('year', models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('APRV', 'Approved'), ('DECL', 'Declined'), ('RESU', 'Resubmitted'), ('CLSD', 'Closed'), ('DUPL', 'Duplicate')], default='OPEN', max_length=4)),
                ('notes', models.TextField(blank=True)),
                ('breeder_comments', models.TextField(blank=True)),
                ('admin_comments', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='cares_smp_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5),
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='cares_smp_year_cap',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='is_smp_club',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='require_fry_rearing_notes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='require_spawning_notes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bapleaderboard',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bapsubmission',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bap_submissions', to='species.species'),
        ),
        migrations.AlterField(
            model_name='bapsubmission',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('APRV', 'Approved'), ('DECL', 'Declined'), ('RESU', 'Resubmitted'), ('CLSD', 'Closed'), ('DUPL', 'Duplicate')], default='OPEN', max_length=4),
        ),
        migrations.CreateModel(
            name='BapTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('BAP', 'BAP'), ('SMP', 'SMP')], max_length=3)),
                ('name', models.CharField(max_length=120)),
                ('threshold_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('icon', models.CharField(blank=True, max_length=20)),
                ('sort_order', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bap_tiers', to='species.aquaristclub')),
            ],
            options={
                'ordering': ['threshold_points'],
            },
        ),
        migrations.CreateModel(
            name='BapYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=240)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('year_label', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLSD', 'Closed')], default='OPEN', max_length=4)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('bap_breeder_of_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bap_breeder_of_year_awards', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_bap_years', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bap_years', to='species.aquaristclub')),
            ],
            options={
                'ordering': ['-year_label', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BapLifetimeTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cares_species_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('aquarist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bap_lifetime_totals', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bap_lifetime_totals', to='species.aquaristclub')),
                ('current_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bap_lifetime_members', to='species.baptier')),
                ('first_award_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bap_lifetime_first_awards', to='species.bapyear')),
                ('last_award_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bap_lifetime_last_awards', to='species.bapyear')),
            ],
            options={
                'ordering': ['-points', '-species_count'],
            },
        ),
        migrations.AddField(
            model_name='bapleaderboard',
            name='bap_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bap_leaderboard_entries', to='species.bapyear'),
        ),
        migrations.AddField(
            model_name='bapsubmission',
            name='bap_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bap_submissions', to='species.bapyear'),
        ),
        migrations.AddConstraint(
            model_name='bapsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'APRV')), fields=('aquarist', 'club', 'species'), name='uniq_approved_bap_species_per_aquarist'),
        ),
        migrations.AddField(
            model_name='smpleaderboard',
            name='aquarist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aquarist_smp_leaderboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smpleaderboard',
            name='bap_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smp_leaderboard_entries', to='species.bapyear'),
        ),
        migrations.AddField(
            model_name='smpleaderboard',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_smp_leaderboards', to='species.aquaristclub'),
        ),
        migrations.AddField(
            model_name='smplifetimetotal',
            name='aquarist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smp_lifetime_totals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smplifetimetotal',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smp_lifetime_totals', to='species.aquaristclub'),
        ),
        migrations.AddField(
            model_name='smplifetimetotal',
            name='current_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smp_lifetime_members', to='species.baptier'),
        ),
        migrations.AddField(
            model_name='smplifetimetotal',
            name='first_award_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smp_lifetime_first_awards', to='species.bapyear'),
        ),
        migrations.AddField(
            model_name='smplifetimetotal',
            name='last_award_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smp_lifetime_last_awards', to='species.bapyear'),
        ),
        migrations.AddField(
            model_name='smpsubmission',
            name='aquarist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aquarist_smp_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smpsubmission',
            name='bap_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smp_submissions', to='species.bapyear'),
        ),
        migrations.AddField(
            model_name='smpsubmission',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_smp_submissions', to='species.aquaristclub'),
        ),
        migrations.AddField(
            model_name='smpsubmission',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smp_submissions', to='species.species'),
        ),
        migrations.AddField(
            model_name='smpsubmission',
            name='speciesInstance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smp_submissions', to='species.speciesinstance'),
        ),
        migrations.AlterUniqueTogether(
            name='baptier',
            unique_together={('club', 'program', 'sort_order')},
        ),
        migrations.AddConstraint(
            model_name='bapyear',
            constraint=models.UniqueConstraint(fields=('club', 'year_label'), name='uniq_bapyear_club_year_label'),
        ),
        migrations.AddConstraint(
            model_name='baplifetimetotal',
            constraint=models.UniqueConstraint(fields=('aquarist', 'club'), name='uniq_bap_lifetime_aquarist_club'),
        ),
        migrations.AddConstraint(
            model_name='smplifetimetotal',
            constraint=models.UniqueConstraint(fields=('aquarist', 'club'), name='uniq_smp_lifetime_aquarist_club'),
        ),
        migrations.AddConstraint(
            model_name='smpsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'APRV')), fields=('aquarist', 'club', 'species', 'bap_year'), name='uniq_approved_smp_species_per_year'),
        ),
        migrations.RunPython(
            code=_backfill_bap_year_and_lifetime_totals,
            reverse_code=_backfill_bap_year_and_lifetime_totals_reverse,
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='auction_fish_slug',
            field=models.CharField(blank=True, help_text="Club slug on auction.fish, e.g. 'pioneer-valley-aquarium-society'", max_length=200),
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='auction_fish_api_key',
            field=species.models.EncryptedTextField(blank=True, help_text='API key for auction.fish (encrypted at rest; never redisplayed after save)'),
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='auction_fish_api_key_hint',
            field=models.CharField(blank=True, help_text="Redacted fingerprint of the stored API key, e.g. 'ck_539d••••1010'", max_length=30),
        ),
        migrations.RenameField(
            model_name='bapimportbatch',
            old_name='auction_name',
            new_name='club_or_auction_name',
        ),
        migrations.RenameField(
            model_name='bapimportbatch',
            old_name='auction_date',
            new_name='auction_pull_date',
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='cares_liaison_name',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='cares_liason_email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='club_api_key',
            field=species.models.EncryptedTextField(blank=True, help_text='Club admin API key for club-scoped API access (encrypted at rest; never redisplayed after save)'),
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='club_api_key_hint',
            field=models.CharField(blank=True, help_text="Redacted fingerprint of the club admin API key, e.g. 'club_539d••••1010'", max_length=30),
        ),
        migrations.CreateModel(
            name='AquaristClubEmailAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_aliases', to='species.aquaristclub')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_email_aliases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Club Email Alias',
                'verbose_name_plural': 'Club Email Aliases',
                'ordering': ['club', 'alias_email'],
                'constraints': [models.UniqueConstraint(fields=('club', 'alias_email'), name='uniq_club_alias_email')],
            },
        ),
        migrations.RemoveField(
            model_name='aquaristclub',
            name='bap_notes_template',
        ),
    ]
