# Generated by Django 5.2.9 on 2026-01-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0014_caresregistration_aquarist_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caresregistration',
            name='aquarist_email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
