# Generated by Django 5.2.9 on 2026-05-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0015_populate_speciescollectionlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesinstance',
            name='collection_point_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_instances', to='species.speciescollectionlocation'),
        ),
        migrations.RenameField(
            model_name='caresregistration',
            old_name='collection_location',
            new_name='collection_location_text',
        ),
        migrations.AddField(
            model_name='caresregistration',
            name='collection_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cares_registrations', to='species.speciescollectionlocation'),
        ),
    ]
