# Generated by Django 5.1.6 on 2025-07-31 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0015_aquaristclub_bap_default_points_bapgenuspoints_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bapgenuspoints',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='bapspeciespoints',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='aquaristclub',
            name='bap_config_file',
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='cares_muliplier',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
