# Generated by Django 5.2.9 on 2026-01-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0015_alter_caresregistration_aquarist_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caresregistration',
            name='aquarist_email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
