# Generated by Django 5.2.9 on 2026-08-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0015_registration_sync_state_and_external_id_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='caresregistration',
            name='species_caresreg_external_id_positive_uniq',
        ),
        migrations.AddField(
            model_name='caresregistration',
            name='submitter_notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='caresapprover',
            name='specialty',
            field=models.CharField(choices=[('RICE', 'Adrianichthyidae - Ricefish'), ('ANAB', 'Anabantidae - Climbing Gouramies'), ('EUKIL', 'Aphaniidae - Eurasian Killifish'), ('SAKIL', 'Aplocheilidae - SE Asia Killifish'), ('MRAIN', 'Bedotiidae - Madagascar Rainbowfish'), ('CHAR', 'Characidae - Tetras'), ('ASCIC', 'Cichlidae - Asia'), ('CACIC', 'Cichlidae - Central America'), ('EACIC', 'Cichlidae - East Africa'), ('LMCIC', 'Cichlidae - Lake Malawi'), ('LTCIC', 'Cichlidae - Lake Tanganyika'), ('LVCIC', 'Cichlidae - Lake Victoria'), ('MACIC', 'Cichlidae - Madagascar'), ('NACIC', 'Cichlidae - North Africa'), ('SACIC', 'Cichlidae - South America'), ('WACIC', 'Cichlidae - West Africa'), ('COBI', 'Cobitidae - True Loaches'), ('CYPR', 'Cyprinidae - Minnows and Carps'), ('CYKIL', 'Cyprinodontidae - Small Killifish (Pupfish)'), ('FUND', 'Fundulidae - North American Killifish'), ('GOBI', 'Gobiidae - Gobies'), ('GOOD', 'Goodeidae - Splitfin Livebearers'), ('LORI', 'Loricariidae - Armoured Catfish'), ('RAIN', 'Melanotaeniidae - Oceania Rainbowfish'), ('SQUE', 'Mochokidae - Upside-down Catfish (Squeakers)'), ('NOTH', 'Nothobranchiidae - African Killifish'), ('BETT', 'Osphronemidae - Bettas'), ('POEC', 'Poeciliidae - Livebearers'), ('PSMU', 'Pseudomugilidae - Blue-eyed Rainbowfish'), ('RIVU', 'Rivulidae - South American Killifish'), ('VALE', 'Valenciidae - Mediteranean Killifish'), ('UDF', 'Undefined')], default='UDF', max_length=5),
        ),
        migrations.AlterField(
            model_name='caresregistration',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('APRV', 'Approved'), ('PEND', 'Pending'), ('DECL', 'Declined'), ('RESU', 'Resubmitted'), ('EXPI', 'Expired'), ('CLSD', 'Closed')], default='OPEN', max_length=4),
        ),
        migrations.AlterField(
            model_name='species',
            name='cares_family',
            field=models.CharField(choices=[('RICE', 'Adrianichthyidae - Ricefish'), ('ANAB', 'Anabantidae - Climbing Gouramies'), ('EUKIL', 'Aphaniidae - Eurasian Killifish'), ('SAKIL', 'Aplocheilidae - SE Asia Killifish'), ('MRAIN', 'Bedotiidae - Madagascar Rainbowfish'), ('CHAR', 'Characidae - Tetras'), ('ASCIC', 'Cichlidae - Asia'), ('CACIC', 'Cichlidae - Central America'), ('EACIC', 'Cichlidae - East Africa'), ('LMCIC', 'Cichlidae - Lake Malawi'), ('LTCIC', 'Cichlidae - Lake Tanganyika'), ('LVCIC', 'Cichlidae - Lake Victoria'), ('MACIC', 'Cichlidae - Madagascar'), ('NACIC', 'Cichlidae - North Africa'), ('SACIC', 'Cichlidae - South America'), ('WACIC', 'Cichlidae - West Africa'), ('COBI', 'Cobitidae - True Loaches'), ('CYPR', 'Cyprinidae - Minnows and Carps'), ('CYKIL', 'Cyprinodontidae - Small Killifish (Pupfish)'), ('FUND', 'Fundulidae - North American Killifish'), ('GOBI', 'Gobiidae - Gobies'), ('GOOD', 'Goodeidae - Splitfin Livebearers'), ('LORI', 'Loricariidae - Armoured Catfish'), ('RAIN', 'Melanotaeniidae - Oceania Rainbowfish'), ('SQUE', 'Mochokidae - Upside-down Catfish (Squeakers)'), ('NOTH', 'Nothobranchiidae - African Killifish'), ('BETT', 'Osphronemidae - Bettas'), ('POEC', 'Poeciliidae - Livebearers'), ('PSMU', 'Pseudomugilidae - Blue-eyed Rainbowfish'), ('RIVU', 'Rivulidae - South American Killifish'), ('VALE', 'Valenciidae - Mediteranean Killifish'), ('UDF', 'Undefined')], default='UDF', max_length=5),
        ),
    ]
