# Generated by Django 5.2.9 on 2026-01-30 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0016_alter_caresregistration_aquarist_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caresregistration',
            name='aquarist',
        ),
        migrations.AlterField(
            model_name='caresregistration',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_registrations', to='species.species'),
        ),
    ]
