# Generated by Django 5.1.6 on 2025-08-02 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0016_alter_bapgenuspoints_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bapgenuspoints',
            name='example_species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example_species_bap_points', to='species.species'),
        ),
    ]
