# Generated by Django 5.2.9 on 2026-05-20

from django.db import migrations


def forwards(apps, schema_editor):
    SpeciesInstance = apps.get_model('species', 'SpeciesInstance')
    CaresRegistration = apps.get_model('species', 'CaresRegistration')
    SpeciesCollectionLocation = apps.get_model('species', 'SpeciesCollectionLocation')

    for si in SpeciesInstance.objects.exclude(collection_point__isnull=True).exclude(collection_point='').iterator():
        name = (si.collection_point or '').strip()
        if not name:
            continue
        loc = SpeciesCollectionLocation.objects.filter(species_id=si.species_id, name__iexact=name).first()
        if loc:
            si.collection_point_fk_id = loc.id
            si.save(update_fields=['collection_point_fk'])

    for reg in CaresRegistration.objects.exclude(collection_location_text__isnull=True).exclude(collection_location_text='').iterator():
        name = (reg.collection_location_text or '').strip()
        if not name or not reg.species_id:
            continue
        loc = SpeciesCollectionLocation.objects.filter(species_id=reg.species_id, name__iexact=name).first()
        if loc:
            reg.collection_location_id = loc.id
            reg.save(update_fields=['collection_location'])


def backwards(apps, schema_editor):
    SpeciesInstance = apps.get_model('species', 'SpeciesInstance')
    CaresRegistration = apps.get_model('species', 'CaresRegistration')

    SpeciesInstance.objects.exclude(collection_point_fk__isnull=True).update(collection_point_fk=None)
    CaresRegistration.objects.exclude(collection_location__isnull=True).update(collection_location=None)


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0016_add_collection_location_foreign_keys'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
