# Generated by Django 5.2.9 on 2026-08-21 19:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0017_aquaristclub_next_member_number_bapimportbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmpLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('year', models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('species_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('is_final', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmpLifetimeTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-points', '-species_count'],
            },
        ),
        migrations.CreateModel(
            name='SmpSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('maintenance_year_number', models.PositiveIntegerField(default=1)),
                ('base_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('smp_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('year', models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('APRV', 'Approved'), ('DECL', 'Declined'), ('RESU', 'Resubmitted'), ('CLSD', 'Closed'), ('DUPL', 'Duplicate')], default='OPEN', max_length=4)),
                ('notes', models.TextField(blank=True)),
                ('breeder_comments', models.TextField(blank=True)),
                ('admin_comments', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='cares_smp_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5),
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='cares_smp_year_cap',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='is_smp_club',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='require_fry_rearing_notes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='require_spawning_notes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bapleaderboard',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bapsubmission',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bap_submissions', to='species.species'),
        ),
        migrations.AlterField(
            model_name='bapsubmission',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('APRV', 'Approved'), ('DECL', 'Declined'), ('RESU', 'Resubmitted'), ('CLSD', 'Closed'), ('DUPL', 'Duplicate')], default='OPEN', max_length=4),
        ),
        migrations.CreateModel(
            name='BapTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('BAP', 'BAP'), ('SMP', 'SMP')], max_length=3)),
                ('name', models.CharField(max_length=120)),
                ('threshold_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('icon', models.CharField(blank=True, max_length=20)),
                ('sort_order', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bap_tiers', to='species.aquaristclub')),
            ],
            options={
                'ordering': ['threshold_points'],
            },
        ),
        migrations.CreateModel(
            name='BapYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=240)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('year_label', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLSD', 'Closed')], default='OPEN', max_length=4)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('bap_breeder_of_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bap_breeder_of_year_awards', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_bap_years', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bap_years', to='species.aquaristclub')),
            ],
            options={
                'ordering': ['-year_label', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BapLifetimeTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cares_species_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('aquarist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bap_lifetime_totals', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bap_lifetime_totals', to='species.aquaristclub')),
                ('current_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bap_lifetime_members', to='species.baptier')),
                ('first_award_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bap_lifetime_first_awards', to='species.bapyear')),
                ('last_award_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bap_lifetime_last_awards', to='species.bapyear')),
            ],
            options={
                'ordering': ['-points', '-species_count'],
            },
        ),
        migrations.AddField(
            model_name='bapleaderboard',
            name='bap_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bap_leaderboard_entries', to='species.bapyear'),
        ),
        migrations.AddField(
            model_name='bapsubmission',
            name='bap_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bap_submissions', to='species.bapyear'),
        ),
        migrations.AddConstraint(
            model_name='bapsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'APRV')), fields=('aquarist', 'club', 'species'), name='uniq_approved_bap_species_per_aquarist'),
        ),
        migrations.AddField(
            model_name='smpleaderboard',
            name='aquarist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aquarist_smp_leaderboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smpleaderboard',
            name='bap_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smp_leaderboard_entries', to='species.bapyear'),
        ),
        migrations.AddField(
            model_name='smpleaderboard',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_smp_leaderboards', to='species.aquaristclub'),
        ),
        migrations.AddField(
            model_name='smplifetimetotal',
            name='aquarist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smp_lifetime_totals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smplifetimetotal',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smp_lifetime_totals', to='species.aquaristclub'),
        ),
        migrations.AddField(
            model_name='smplifetimetotal',
            name='current_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smp_lifetime_members', to='species.baptier'),
        ),
        migrations.AddField(
            model_name='smplifetimetotal',
            name='first_award_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smp_lifetime_first_awards', to='species.bapyear'),
        ),
        migrations.AddField(
            model_name='smplifetimetotal',
            name='last_award_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smp_lifetime_last_awards', to='species.bapyear'),
        ),
        migrations.AddField(
            model_name='smpsubmission',
            name='aquarist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aquarist_smp_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smpsubmission',
            name='bap_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smp_submissions', to='species.bapyear'),
        ),
        migrations.AddField(
            model_name='smpsubmission',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_smp_submissions', to='species.aquaristclub'),
        ),
        migrations.AddField(
            model_name='smpsubmission',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smp_submissions', to='species.species'),
        ),
        migrations.AddField(
            model_name='smpsubmission',
            name='speciesInstance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smp_submissions', to='species.speciesinstance'),
        ),
        migrations.AlterUniqueTogether(
            name='baptier',
            unique_together={('club', 'program', 'sort_order')},
        ),
        migrations.AddConstraint(
            model_name='bapyear',
            constraint=models.UniqueConstraint(fields=('club', 'year_label'), name='uniq_bapyear_club_year_label'),
        ),
        migrations.AddConstraint(
            model_name='baplifetimetotal',
            constraint=models.UniqueConstraint(fields=('aquarist', 'club'), name='uniq_bap_lifetime_aquarist_club'),
        ),
        migrations.AddConstraint(
            model_name='smplifetimetotal',
            constraint=models.UniqueConstraint(fields=('aquarist', 'club'), name='uniq_smp_lifetime_aquarist_club'),
        ),
        migrations.AddConstraint(
            model_name='smpsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'APRV')), fields=('aquarist', 'club', 'species', 'bap_year'), name='uniq_approved_smp_species_per_year'),
        ),
    ]
