# Generated by Django 5.1.6 on 2025-08-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0017_bapgenuspoints_example_species'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bapgenuspoints',
            options={'ordering': ['name'], 'verbose_name_plural': 'BapGenusPoints'},
        ),
        migrations.AlterModelOptions(
            name='bapspeciespoints',
            options={'ordering': ['name'], 'verbose_name_plural': 'BapSpeciesPoints'},
        ),
        migrations.AddField(
            model_name='bapgenuspoints',
            name='species_override_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
