# Generated by Django 5.2.9 on 2026-02-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0017_remove_caresregistration_aquarist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Full Instagram URL (e.g., https://instagram.com/username)', null=True, verbose_name='Instagram Profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Full Facebook URL (e.g., https://facebook.com/username)', null=True, verbose_name='Facebook Profile'),
        ),        
        migrations.AddField(
            model_name='user',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Full YouTube URL (e.g., https://youtube.com/@username)', null=True, verbose_name='YouTube Channel'),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_manager',
            new_name='is_species_admin',
        ),        
    ]
