# Generated by Django 5.1.6 on 2025-08-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0018_alter_bapgenuspoints_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bapgenuspoints',
            name='species_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
