# Generated by Django 5.2.9 on 2026-02-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0018_add_social_media_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefer_tile_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='global_region',
            field=models.CharField(choices=[('SAM', 'South America'), ('CAM', 'Central America'), ('NAM', 'North America'), ('AFR', 'Africa'), ('SEA', 'Southeast Asia'), ('AUS', 'Oceania'), ('EUR', 'Europe'), ('OTH', 'Other Region')], default='AFR', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook Profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram Profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube Channel'),
        ),
    ]
