# Generated by Django 5.1.6 on 2025-08-05 13:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0019_bapgenuspoints_species_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BapGenusPoints',
            new_name='BapGenus',
        ),
        migrations.RenameModel(
            old_name='BapSpeciesPoints',
            new_name='BapSpecies',
        ),       
    ] 
