# Generated by Django 5.1.6 on 2025-08-07 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0020_rename BapSpeciePoints and BapGenusPoints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bapgenus',
            options={'ordering': ['name'], 'verbose_name_plural': 'BapGenus'},
        ),
        migrations.AlterModelOptions(
            name='bapspecies',
            options={'ordering': ['name'], 'verbose_name_plural': 'BapSpecies'},
        ),
        migrations.AddField(
            model_name='bapsubmission',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bapsubmission',
            name='request_points_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bapgenus',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_bap_genus', to='species.aquaristclub'),
        ),
        migrations.AlterField(
            model_name='bapgenus',
            name='example_species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example_bap_species', to='species.species'),
        ),
        migrations.AlterField(
            model_name='bapspecies',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_bap_species', to='species.aquaristclub'),
        ),
        migrations.AlterField(
            model_name='bapspecies',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bap_species', to='species.species'),
        ),
    ]
