# Generated by Django 5.2.9 on 2026-08-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0020_auctionfish_fields_and_bapimportbatch_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaristclub',
            name='cares_liaison_name',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='cares_liason_email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
