# Generated by Django 5.1.6 on 2025-08-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0021_alter_bapgenus_options_alter_bapspecies_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaristclub',
            name='acronym',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
