# Generated by Django 5.2.9 on 2026-08-24 15:15

import species.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0021_aquaristclub_cares_liaison_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaristclub',
            name='bap_report_api_key',
            field=species.models.EncryptedTextField(blank=True, help_text='Club-generated API key for the BAP species-instance report sync (encrypted at rest; never redisplayed after generation)'),
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='bap_report_api_key_hint',
            field=models.CharField(blank=True, help_text="Redacted fingerprint of the stored BAP report API key, e.g. 'bap_539d••••1010'", max_length=30),
        ),
    ]
