# Generated by Django 5.1.6 on 2025-08-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0022_aquaristclub_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaristclub',
            name='require_member_approval',
            field=models.BooleanField(default=True),
        ),
    ]
