# Generated by Django 5.1.6 on 2025-08-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0023_aquaristclub_require_member_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bapsubmission',
            name='comments',
        ),
        migrations.AddField(
            model_name='bapsubmission',
            name='admin_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bapsubmission',
            name='breeder_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
