# Generated by Django 5.1.6 on 2025-08-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0024_remove_bapsubmission_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aquaristclubmember',
            old_name='membership_admin',
            new_name='is_club_admin',
        ),
        migrations.AddField(
            model_name='aquaristclub',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
