# Generated by Django 5.1.6 on 2025-08-20 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0025_rename_membership_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciescomment',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_comments', to='species.species'),
        ),
        migrations.AlterField(
            model_name='speciesinstance',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='species_instances', to='species.species'),
        ),
        migrations.AlterField(
            model_name='speciesinstancecomment',
            name='speciesInstance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_instance_comments', to='species.speciesinstance'),
        ),
        migrations.AlterField(
            model_name='speciesinstancelabel',
            name='speciesInstance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_instance_labels', to='species.speciesinstance'),
        ),
        migrations.AlterField(
            model_name='speciesinstancelogentry',
            name='speciesInstance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='species_instance_log_entries', to='species.speciesinstance'),
        ),
        migrations.AlterField(
            model_name='speciesmaintenancelogentry',
            name='speciesMaintenanceLog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_maintenance_log_entries', to='species.speciesmaintenancelog'),
        ),
        migrations.AlterField(
            model_name='speciesreferencelink',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_links', to='species.species'),
        ),
    ]
