# Generated by Django 5.2.9 on 2026-08-28 16:44

from django.db import migrations


# Ported verbatim from 0002_seed_action_types.
def _seed_action_types(apps, schema_editor):
    ActionType = apps.get_model('pending_actions', 'ActionType')
    ActionType.objects.update_or_create(
        slug='cares_status_change',
        defaults={
            'display_name': 'CARES status change notification',
            'email_template': 'pending_actions/cares_status_change_email.html',
            'response_form_class': 'pending_actions.forms.ConfirmPendingActionForm',
            'default_ttl_hours': 72,
            'is_active': True,
        },
    )
    ActionType.objects.update_or_create(
        slug='cares_new_registration_notification',
        defaults={
            'display_name': 'CARES new registration notification',
            'email_template': 'species/cares/email_new_registration.html',
            'response_form_class': '',
            'default_ttl_hours': 72,
            'is_active': True,
        },
    )


def _unseed_action_types(apps, schema_editor):
    ActionType = apps.get_model('pending_actions', 'ActionType')
    ActionType.objects.filter(slug__in=['cares_status_change', 'cares_new_registration_notification']).delete()


# Ported verbatim from 0004_seed_proxy_invite_action_type.
def _seed_proxy_invite(apps, schema_editor):
    ActionType = apps.get_model('pending_actions', 'ActionType')
    ActionType.objects.update_or_create(
        slug='proxy_user_invite',
        defaults={
            'display_name': 'Proxy user account invitation',
            'email_template': 'pending_actions/proxy_invite_email.html',
            'response_form_class': '',
            'default_ttl_hours': 168,   # 7 days — reasonable window for a human to act on an invite
            'is_active': True,
        },
    )


def _unseed_proxy_invite(apps, schema_editor):
    ActionType = apps.get_model('pending_actions', 'ActionType')
    ActionType.objects.filter(slug='proxy_user_invite').delete()


# Ported verbatim from 0005_seed_bap_join_invite_action_type.
def _seed_bap_join_invite(apps, schema_editor):
    ActionType = apps.get_model('pending_actions', 'ActionType')
    ActionType.objects.get_or_create(
        slug='bap_join_invite',
        defaults={
            'display_name': 'BAP club join invitation',
            'email_template': 'pending_actions/bap_join_invite_email.html',
            'response_form_class': '',
            'default_ttl_hours': 168,
            'is_active': True,
        },
    )


def _remove_bap_join_invite(apps, schema_editor):
    ActionType = apps.get_model('pending_actions', 'ActionType')
    ActionType.objects.filter(slug='bap_join_invite').delete()


# Ported verbatim from 0006_seed_bap_notes_required_action_type.
def _seed_bap_notes_required(apps, schema_editor):
    ActionType = apps.get_model('pending_actions', 'ActionType')
    ActionType.objects.get_or_create(
        slug='bap_notes_required',
        defaults={
            'display_name': 'BAP/SMP required notes request',
            'email_template': 'pending_actions/bap_notes_required_email.html',
            'response_form_class': 'pending_actions.forms.BapNotesRequiredForm',
            'default_ttl_hours': 168,
            'is_active': True,
        },
    )


def _remove_bap_notes_required(apps, schema_editor):
    ActionType = apps.get_model('pending_actions', 'ActionType')
    ActionType.objects.filter(slug='bap_notes_required').delete()


class Migration(migrations.Migration):

    replaces = [('pending_actions', '0002_seed_action_types'), ('pending_actions', '0003_rename_pending_action_status_idx'), ('pending_actions', '0004_seed_proxy_invite_action_type'), ('pending_actions', '0005_seed_bap_join_invite_action_type'), ('pending_actions', '0006_seed_bap_notes_required_action_type')]

    dependencies = [
        ('pending_actions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=_seed_action_types,
            reverse_code=_unseed_action_types,
        ),
        migrations.RenameIndex(
            model_name='pendingaction',
            new_name='pending_action_status_idx',
            old_name='pending_act_status_e1d79f_idx',
        ),
        migrations.RunPython(
            code=_seed_proxy_invite,
            reverse_code=_unseed_proxy_invite,
        ),
        migrations.RunPython(
            code=_seed_bap_join_invite,
            reverse_code=_remove_bap_join_invite,
        ),
        migrations.RunPython(
            code=_seed_bap_notes_required,
            reverse_code=_remove_bap_notes_required,
        ),
    ]
