# Generated by Django 5.2.9 on 2026-08-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pending_actions', '0002_seed_action_types'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pendingaction',
            new_name='pending_action_status_idx',
            old_name='pending_act_status_e1d79f_idx',
        ),
    ]
